
export class Complaints {

    tnbLogo: string;


    kupmUser: boolean;
    noticeA: boolean;
    claiminform: boolean;

    owner: boolean;
    tenant: boolean;
    staff: boolean;
    heir: boolean;

    formIndicator: boolean;
    formType: string;

    serialNum: string;

    notWillingSign: boolean;
    noClient: boolean;

    state: string;
    state2: string
    date1: string;
    date2: string;
    date3: string;
    dated: string;
    absent: boolean;
    present: boolean;
    notAbsent: boolean;
    inspectDate: string;
    inspectDateUntil: string;
    customername: string;
    customeraddress: string;
    anamoly: string;
    subsection1: boolean;
    subsection2: boolean;
    subsection3: boolean;
    subsection4: boolean;
    subsection5: boolean;
    subsection6: boolean;
    subsection7: boolean;
    subsection8: boolean;
    subsectionBase1: string;
    subsectionBase2: string;
    subsectionBase3: string;
    subsectionBase4: string;
    subsectionBase5: string;
    subsectionBase6: string;
    subsectionBase7: string;
    subsectionBase8: string;
    verifySign: string;
    managerSign: string;
    deliverSign: string;
    receiverSign: string;
    disconnectSign: string;
    reconnectorSign: string;
    deliveryDate: string;
    deliveryTime: string;
    deliverName: string;
    receiverName: string;
    supplyDiscDate: string;
    supplyDiscTime: string;
    supplyDiscName: string;
    supplyReconDate: string;
    supplyReconTime: string;
    supplyReconName: string;
    officeAddressCheck: string;
    officeAddress: string;
    officePhoneNo: string;
    evidenceItem: any;
    stffSign: any;
    witnessSign: any;
    currentDateCollect: string;
    currentTime: string;
    wtinessName: string;
    purpose: string;
    position: string;
    department: string;
    condition: string;
    datesubsection38: string;
    licenseholdername: string;
    licenseaddress: string;
    licensedate: string;//pagebreaks
    yourrefapp7: string;
    ourrefapp7: string;
    dateapp7: string;
    date1app7: string;
    date2app7: string;
    officeno: string;
    manager: string;//pagebreaks
    to: string;
    from: string;
    interuptedTime: string;
    until: string;
    time: string;
    staffNameCheck: any;
    staffname: string;
    staffno: string;
    name: string;
    nric: number;
    nricWitness: number;
    nriceStaff: number;
    datetime: string;
    condi: boolean;
    officeName: string;
    remark1: string;
    remark2: string;
    remark3: string;
    remark4: string;
    remark5: string;
    tempAddress: any;
    station: any;


    ta4position: string;
    ta4executivename: string;
    ta4executiveposition: string;
    ta4executivesign: any;
    ta4reportno: number;
    ta4currentDate: any;

    ta4cooperate: any;
    ta4statename: string;
    ta4anamoly: string
    ta4ss1tampers: boolean;
    ta4ss3abstracts: boolean;
    ta4ss3consumer: boolean;
    ta4ss3uses: boolean;
    ta4ss3afterindex: boolean;
    ta4ss3prevents: boolean;
    ta4ss14damages: boolean;
    ta4disconnection: string;
    ta4datetime: string;
    ta4starttime: string;
    ta4endtime: string;
    ta4custname: string;
    ta4accountno: string;
    ta4staffname: string;
    ta4staffindetard: string;
    ta4staffno: string;
    ta4designation: string;
    ta4purpose: string;
    ta4custidenkard: string;
    ta4agree: boolean;
    ta4indatetime: string;
    ta4officezone: string;
    ta4officeaddress: string;
    ta4officephone: string;
    ta4department: string;
    ta4custstatus: string;
    ta4witnessidencard: string;
    ta4witnessadress: string;
    ta4custaddress: string;
    ta4item: string;
    ta4describe: string;
    ta4serialNum: string;
}