export enum Domains {
    TA0ALNDOMAIN = 'TA0ALNDOMAIN',
    TA0AMI = 'TA0AMI',
    TA0ANOMALYMAIN = 'TA0ANOMALYMAIN',
    TA0ANOMALYCATEGORY = 'TA0ANOMALYCATEGORY',
    TA0ANOMALYTYPE = 'TA0ANOMALYTYPE',
    TA0CORRECTIVECODE = 'TA0CORRECTIVECODE',
    TA0DEVICECATEGORY = 'TA0DEVICECATEGORY',
    TA0DEVICELOCATION = 'TA0DEVICELOCATION',
    TA0FUNCTIONCLASS = 'TA0FUNCTIONCLASS',
    TA0INITIATIVE = 'TA0INITIATIVE',
    TA0INSTALLATION = 'TA0INSTALLATION',
    TA0MRNOTE = 'TA0MRNOTE',
    TA0MRTYPE = 'TA0MRTYPE',
    TA0SNCODE = 'TA0SNCODE',
    TA0TESTTYPE = 'TA0TESTTYPE',
    TA0VALUATIONTYPE = 'TA0VALUATIONTYPE',  //add valuation type 
    // Seal : Sil & Sticker (Alif - 19-03-2019)
    TA4SAFETYSTICKER = 'TA4SAFETYSTICKER',
    TA4SCFUSE = 'TA4SCFUSE',
    TA4SCMETERCOVER = 'TA4SCMETERCOVER',
    TA4SCMETERPANEL = 'TA4SCMETERPANEL',
    TA4SCPANELCT = 'TA4SCPANELCT',
    TA4SCTERMCT = 'TA4SCTERMCT',
    TA4SCTERMMETER = 'TA4SCTERMMETER',
    TA4SCTTB = 'TA4SCTTB',
    TA4TSMETER = "TA4TSMETER",
    TA4TSFUSE = "TA4TSFUSE",
    TA4TSTTB = "TA4TSTTB",
    TA4TSCURRENTRATIO = "TA4TSCURRENTRATIO",
    TA4TSWIRING = "TA4TSWIRING",
    TA4ZONE = 'TA4ZONE',
    TA4SC = 'TA4SC',
    TA4METERTYPE = 'TA4METERTYPE',
    TA0SEALREMREASON = 'TA0SEALREMREASON',


    //json Local Domains.
    LPCWORKORDER = 'LPCWORKORDER',
    WoNumActive = 'WONUMACTIVE',
    AlnDomain = 'ALNDOMAIN',
    AssetDetails = 'ASSETDETAILS',
    UserStatus = 'USERSTATUS',
    SnCode = 'SNCODE',
    MaterialData = 'MATERIALDATA',
    CustomerData = 'CUSTOMERDATA',
    WindingGroup = 'WINDINGGROUP',
    AmiData = 'AMIDATA',
    UserDetails = 'USERDETAILS',
    // Add for zone only
    Zone = 'ZONE',

    // data fetch service 
    DATA_FETCH_ASSIGNWORK = 'ASSIGNWORK',
    DATA_FETCH_TAOSUPERVISORS0 = 'ta0SupervisorSO',

    //Executive
    Executive = 'TA4SEALEXECUTIVE',
    TeamMembers = 'TA4MEMBERS',
    SiteID = 'SITEID'
    
}