export enum FunctionClass {
    COM_SMTR = 'COM_SMTR',
    MODEM = 'MODEM',
    NMTR = 'NMTR',
    RMTR = 'RMTR',
    SIMCRD = 'SIMCRD',
    SMTR = 'SMTR',
    SMTR_OLD = 'SMTR_OLD',
    SMTR_CM = 'SMTR_CM',
    CTTFR = 'CTTFR',
    CTDIR = 'CTDIR',
    VTDIR = 'VTDIR',
    PTTFR = 'PTTFR',

    COM_SMTR_DESC = 'Comm Module for Smart Meter',
    MODEM_DESC = 'Modem',
    NMTR_DESC = 'Normal Meter',
    RMTR_DESC = 'RMR Meter',
    SIMCRD_DESC = 'SIM Card',
    SMTR_DESC = 'Smart Meter',
    SMTR_CM_DESC = 'Smart Meter w/ Comm Module Req',
    CTTFR_DESC = 'CT Instrument Transformer',
    PTTFR_DESC = 'PT Instrument Transformer',
    VTTFR_DESC = 'VT Instrument Transformer',


    // Seal
    METER_COVER = "METER_COVER",
    TERMINAL_COVER = "TERMINAL_COVER",
    METER_FUSE = "METER_FUSE",
    MD_BUTTON = "MD_BUTTON",
    METER_BATTERY = "METER_BATTERY",
    OPTICAL_EYE_COVER = "OPTICAL_EYE_COVER",
    METER_CONDITION = "METER_CONDITION",
    TERMINAL_CONDITION = "TERMINAL_CONDITION",


    TTB = "TEST_BLOCK",
    // Other Seal (MVHV)
    PT_CHAM = "PT_CHAMBER",
    CT_CHAM = "CT_CHAMBER",
    PT_SEC_FS = "PT_SEC_FUSE",
    METER_KIOSK = "KIOSK_PANELDOOR",
    METER_TEST_BOX = "METER_TEST_BOX",
    TERMINATION_BOX = "TERMINATION_BOX",
    MARSHALLING_BOX = "MARSHALLING_BOX",
    // Other Seal (LV)
    CT_PANEL = "CT_CHAMBER",
    PANEL_METER = "PANEL_METER",
    TERMINAL_CT = "TERMINAL_CT",
    MODEM_ = "MODEM",
    COMM_MODULE = "COMM_MODULE",

    // Sticker
    STERMINAL_COVER = "TERMINAL_COVER",
    SMETER_FUSE = "METER_FUSE",
    STTB = "TEST_BLOCK",
    // Other Sticker (MVHV)
    SPT_CHAM = "PT_CHAMBER",
    SCT_CHAM = "CT_CHAMBER",
    SPT_SEC_FS = "PT_SEC_FUSE",
    SMETER_KIOSK = "KIOSK_PANELDOOR",
    SMETER_TEST_BOX = "METER_TEST_BOX",
    STERMINATION_BOX = "TERMINATION_BOX",
    SMARSHALLING_BOX = "MARSHALLING_BOX",
    // Other Sticker (LV)
    SCT_PANEL = "CT_CHAMBER",
    SPANEL_METER = "PANEL_METER",
    STERMINAL_CT = "TERMINAL_CT",
    SMODEM_ = "MODEM",

    S_STICKER = "STICKER_SAFETY",
    TERMINAL_CT_RED = "TERMINAL_CT_RED",
    TERMINAL_CT_YELLOW = "TERMINAL_CT_YELLOW",
    TERMINAL_CT_BLUE = "TERMINAL_CT_BLUE",

    //Crimpless Seal
    TEST_BLOCK_F1_1 = "TEST_BLOCK_F1_1",
    TEST_BLOCK_F1_2 = "TEST_BLOCK_F1_2",
    TEST_BLOCK_F2_1 = "TEST_BLOCK_F2_1",
    TEST_BLOCK_F2_2 = "TEST_BLOCK_F2_2",
    TEST_BLOCK_F3_1 = "TEST_BLOCK_F3_1",
    TEST_BLOCK_F3_2 = "TEST_BLOCK_F3_2",
    METER_FUSE_F1 = "METER_FUSE_F1",
    METER_FUSE_F2 = "METER_FUSE_F2",
    METER_FUSE_F3 = "METER_FUSE_F3",
    KIOSK1_PANELDOOR_1 = "PANELDOOR_KIOSK1_1",
    KIOSK1_PANELDOOR_2 = "PANELDOOR_KIOSK1_2",

    KIOSK2_PANELDOOR_1 = "PANELDOOR_KIOSK2_1",
    KIOSK2_PANELDOOR_2 = "PANELDOOR_KIOSK2_2",

    METER_TESTBOX_KIOSK1_1 = "METER_TESTBOX_KIOSK1_1",
    METER_TESTBOX_KIOSK1_2 = "METER_TESTBOX_KIOSK1_2",

    METER_TESTBOX_KIOSK2_1 = "METER_TESTBOX_KIOSK2_1",
    METER_TESTBOX_KIOSK2_2 = "METER_TESTBOX_KIOSK2_2",
    

    CT_CHAMBER_F1 = "CT_CHAMBER_F1",
    CT_CHAMBER_F2 = "CT_CHAMBER_F2",
    CT_CHAMBER_F3 = "CT_CHAMBER_F3",
    PT_CHAMBER_F1 = "PT_CHAMBER_F1",
    PT_CHAMBER_F2 = "PT_CHAMBER_F2",
    PT_CHAMBER_F3 = "PT_CHAMBER_F3",
    TERMINATION_BOX_F1 = "TERMINATION_BOX_F1",
    TERMINATION_BOX_F2 = "TERMINATION_BOX_F2",
    TERMINATION_BOX_F3 = "TERMINATION_BOX_F3",
    MARSHALLING_BOX_F1 = "MARSHALLING_BOX_F1",
    MARSHALLING_BOX_F2 = "MARSHALLING_BOX_F2",
    MARSHALLING_BOX_F3 = "MARSHALLING_BOX_F3",
    PT_SEC_FUSE_F1 = "PT_SEC_FUSE_F1",
    PT_SEC_FUSE_F2 = "PT_SEC_FUSE_F2",
    PT_SEC_FUSE_F3 = "PT_SEC_FUSE_F3",

}