export interface User {
  emailId: string;
  userName: string;
  primaryRole: string;
  status: string;
  description: string;
  orgId: string;
  companyName: string;
  logoUrl: string;
  logoIconUrl: string;
  userGroupId: string;
  add1: string;
  add2: string;
  postcode: string;
   city: string;
  state: string;
  userPicUrl: string;
  userPicUrlNormal: string;
  userPicUrlProfile: string;
  telephone: string;
  mobile: string;
  fax: string;
  commeMail:string;
	language:string;
	workareadesc:string;
	selfIntro:string;
	gender:string;
  nickname:string;
  acclastupdate:any;
  userType:string;
  biznetwork:string;
  bizenabledate:any;
  bizprofile:string;
  bizad:string;
  accid: any;
  pdpa: string;
  dbStatus: string;
  agreeConditions: string;
  addressQuestions: string;
}